# -*- coding: utf-8 -*-
"""ModelTraining.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fwCvoDBQ5-tSfscTGbH3vYwj5AZtXcPG
"""

!pip install gdown

import gdown

file_id = "1MCfRkOhVJwDNqAz5j_DwCfIFKqc373Kd"

download_url = f"https://drive.google.com/uc?id={file_id}"

output_file = "dataset.csv"

gdown.download(download_url, output_file, quiet=False)

import pandas as pd
data = pd.read_csv(output_file)

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
features = scaler.fit_transform(data[["HR", "BT", "SpO2", "Age", "Gender"]])

X = features
y = data["Outcome"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = ExtraTreesClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

outcome_counts = data["Outcome"].value_counts()